version: '3.7'

services:
  ossa:
    image: node:16.19.0-bullseye-slim
    restart: always
    volumes:
      - ./:/src
    container_name: unkaos-ossa
    ports:
      - '3004:3004'
    command: npx ts-node /src/ossa/index.ts
  cerberus:
    image: node:16.19.0-bullseye-slim
    restart: always
    volumes:
      - ./:/src
    container_name: unkaos-cerberus
    ports:
      - '3005:3005'
    command: npx ts-node /src/cerberus/index.ts
  zeus:
    image: node:16.19.0-bullseye-slim
    restart: always
    volumes:
      - ./:/src
    container_name: unkaos-zeus
    ports:
      - '3006:3006'
    command: npx ts-node /src/zeus/index.ts
  gateway:
    image: node:16.19.0-bullseye-slim
    restart: always
    volumes:
      - ./:/src
    container_name: unkaos-gateway
    ports:
      - '3001:3001'
    command: npx ts-node /src/gateway/index.ts
  hermes:
    image: node:16.19.0-bullseye-slim
    restart: always
    volumes:
      - ./:/src
    container_name: unkaos-hermes
    ports:
      - '5009:5009'
    command: npx ts-node /src/hermes/index.ts

  athena:
    image: node:16.19.0-bullseye-slim
    restart: always
    volumes:
      - ./:/src
    container_name: unkaos-athena
    ports:
      - '5010:5010'
    command: npx ts-node /src/athena/index.ts


#  nginx:
#    image: nginx:alpine
#    restart: always
#    volumes:
#      - /var/app/unkaos/server/nginx/logs:/var/log/nginx
#      - /srv/tls/certs:/etc/pki/tls/certs
#      - /srv/tls/keys:/etc/pki/tls/private
#      - /var/app/unkaos/server/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - /var/app/unkaos/server/nginx/conf.d:/etc/nginx/conf.d
#      - /var/app/unkaos/server/www:/var/www
#    container_name: unkaos-nginx
#    ports:
#      - '80:80'
#      - '443:443'
#      - '3003:3003'
 #     - '3002:3002'